version: '3'
services:
  mosdns:
    image: miniers/mosdns:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    environment:
      - GEO_CDN=cdn.jsdelivr.net
    restart: always
    container_name: mosdns