plugin:
  - tag: log        # 日志
    type: logger
    args:
      level: info

  - tag: main_server    # 启动服务器
    type: server
    args:
      entry: pipeline
      max_concurrent_queries: 0
      server:
        - protocol: udp
          addr: 0.0.0.0:53
        - protocol: tcp
          addr: 0.0.0.0:53

  ################# 可执行插件 ################

  - tag: pipeline
    type: pipeline
    args:
      pipe:
        - _default_cache          # 缓存
        - main_sequence           # 处理请求的主要执行序列

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain    # 处理已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
          goto: _end

        - if:
            - query_is_local_domain   # 处理已知的本地域名
            - !_query_is_common       # 和不常见的请求类型
          exec:
            - forward_local
          goto: _end

        - if:
            - query_is_non_local_domain  # 处理已知的非本地域名
          exec:
            - forward_remote
          goto: _end

        - sequence_bypass_local   # 用 IP 分流未知域名。有两种方案：顺序或并行。这是顺序执行。
      # - parallel_bypass_local   # 如果想用类似 ChinaDNS 的并发分流逻辑。用这个。

  - tag: sequence_bypass_local        # 顺序执行的分流逻辑
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果应答包含本地 IP
          goto: _end                  # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

  - tag: parallel_bypass_local        # 并发执行的分流的逻辑
    type: parallel
    args:
      exec:
        - - forward_local               # 并发请求本地和远程服务器
          - if:
              - !response_has_local_ip  # 如果本地服务器返回的非本地 IP
            exec:
              - _drop_response          # 应答会被丢弃
        - - forward_remote

  - tag: forward_local # 转发至本地服务器的插件
    type: forward
    args:
      upstream:
        - addr: 119.29.29.29
        - addr: 223.5.5.5

  - tag: forward_remote # 转发至远程服务器的插件
    type: fallback
    args:
      primary:            # 主要执行序列。执行序列说明见 `sequence` 插件的 `exec` 参数。
        - forward_clash_dns
      secondary:          # 次要执行序列。同上。
        - forward_local
      stat_length: 30     # 统计长度。默认 10。
      threshold: 10        # 触发阈值。不可大于统计长度。默认 5。
  
  - tag: forward_clash_dns # 转发至远程服务器的插件
    type: forward
    args:
      upstream:
        - addr: 198.18.0.2

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:cn

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:geolocation-!cn

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:category-ads-all

  - tag: response_has_local_ip        # 匹配本地 IP的插件
    type: response_matcher
    args:
      ip:
        - ./geoip.dat:cn

include: [ ]