log:
  level: info

plugin:

  ################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
            - _end

        - if:
            - query_is_local_domain   # 已知的本地域名
            - "!_query_is_common"     # 和不常见的请求类型
          if_and:
            - "!domain_is_force_proxy"  
          exec:
            - forward_local           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
            - domain_is_force_proxy  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - _end

          # 剩下的域名用 IP 分流。
          # 有两种方案："顺序分流"或"并发分流"。
          # 下面的是"顺序分流"的配置。

        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果应答包含本地 IP
          exec:
            - _end                # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

  - tag: forward_local                # 转发至本地服务器的插件
    type: fast_forward
    args:
      upstream:
        - addr: 'https://223.5.5.5/dns-query'
          trusted: true
          dial_addr: '223.5.5.5:443'
        - addr: 'https://doh.pub/dns-query'
          trusted: true
          dial_addr: '120.53.80.136:443'

  - tag: forward_remote               # 转发至远程服务器的插件
    type: sequence
    args:
      exec:
        - primary:            # 主要执行序列。执行序列说明见 `sequence` 插件的 `exec` 参数。
            - forward_clash_dns
          secondary:          # 次要执行序列。同上。
            - forward_local
          # stat_length: 30     # 统计长度。默认 10。
          # threshold: 10        # 触发阈值。不可大于统计长度。默认 5。
          fast_fallback: 200    # 快速 fallback 触发阈值。单位: 毫秒。默认: 0，禁用快速 fallback。可省略。
          always_standby: true # 快速 fallback secondary 始终待命。可省略。
      
  - tag: forward_clash_dns # 转发至远程服务器的插件
    type: fast_forward
    args:
      upstream:
        - addr: 198.18.0.2
  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:cn"
        - "ext:./direct.txt"  

  - tag: domain_is_force_proxy         # 强制远端解析
    type: query_matcher
    args:
      domain:
        - "ext:./proxy.txt"

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:geolocation-!cn"

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:category-ads-all"
        - "ext:./block.txt"

  - tag: response_has_local_ip        # 匹配本地 IP的插件
    type: response_matcher
    args:
      ip:
        - "ext:./geoip.dat:cn"

  - tag: "dns_cache"
    type: cache
    args:
      # 内存缓存。
      size: 5024            # 缓存大小。单位: 条。默认: 1024。
      # cleaner_interval: 120 # 回收器扫描间隔。单位: 秒。默认: 120。一般无需修改。
  

  ################# 服务插件 ################

  - tag: main_server      # 启动服务器
    type: server
    args:
      entry:
        - dns_cache  # 缓存
        - _single_flight  # 去除重复请求
        - main_sequence
      max_concurrent_queries: 0
      server:
        - protocol: udp
          addr: 0.0.0.0:53
        - protocol: tcp
          addr: 0.0.0.0:53
