#!/usr/bin/with-contenv ash
if [ $ENABLE_CFST == 'true' ]; then
    echo -e "开启CFST：$ENABLE_CFST \n"
    if [ ! -f /crontab.bak ]; then
        touch /crontab.bak
    fi
    echo "10 2 * * * /usr/bin/get-best-ip" >> /crontab.bak
    /usr/bin/get-best-ip &
fi

